from time import sleep
import os

def real_val(s):
    return int(s.split('-')[1])

while True:
    files = os.listdir()
    print('Cleaning')

    deleteable = []
    d2 = []
    d3 = []
    for file in files:
        if ".hlt" in file:
            os.remove(file)
        if "AutoGenerated" in file: deleteable.append(file)
        if "conv2-" in file: d3.append(file)
        if "conv-" in file: d2.append(file)
    deleteable.sort(key=real_val)
    d2.sort(key=real_val)
    d3.sort(key=real_val)
    if len(deleteable) > 3:
        for file in deleteable[:-3]:
            os.remove(file)
    if len(d2) > 3:
        for f in d2[:-3]:
            os.remove(f)
    if len(d3) > 3:
        for f in d3[:-3]:
            os.remove(f)
    sleep(10)
